spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_cms
    username: portfolio_admin
    password: StrongPassword123!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  security:
    jwt-secret: ChangeThisToAReallyLongRandomSecretKeyOfAtLeast32Characters
    jwt-expiration: 3600000
    refresh-expiration: 604800000

  bootstrap:
    admin:
      first-name: Saji
      last-name: Joseph
      email: admin@portfolio.local
      password: Admin@123456
